#!/bin/bash
mkdir -p /var/log/vyatta/
touch /var/log/vyatta/vyatta-config-loader.log
touch /var/log/vyatta/vyatta-commit.log
chown ugo+rwX /var/log/vyatta/
chgrp -R vyattacfg /var/log/vyatta/

source /opt/vyatta/etc/functions/script-template
sg vyattacfg -c  "/opt/vyatta/sbin/vyatta-boot-config-loader /config.init" 

