#!/bin/bash
source /opt/vyatta/etc/functions/script-template
sleep 5
session_env=$(/bin/cli-shell-api getSessionEnv $PPID)
eval $session_env 
/bin/cli-shell-api setupSession
/bin/cli-shell-api loadFile /config.init
/opt/vyatta/sbin/my_commit
${vyatta_sbindir}/vyatta-save-config.pl
/bin/cli-shell-api teardownSession
